version: "3.9"

services: 
    database_ignite:
        image: postgres
        env_file:
            - ./.env
        container_name: database_ignite
        restart: always
        ports: 
            - $POSTGRES_PORT:5432
        environment: 
            - POSTGRES_USER=$POSTGRES_PORT_USER
            - POSTGRES_PASSWORD=$POSTGRES_PORT_PASSWORD
            - POSTGRES_DB=$POSTGRES_PORT_NAME
        volumes:
            - pgdata:/data/postgres

    redis:
        image: redis:alpine
        ports:
            - 6379:6379

    # app:
    #     build: .
    #     container_name: rentx
    #     ports: 
    #         - 3333:3333
    #     volumes: 
    #         - .:/usr/app
    #     links:
    #         - database_ignite
    #     depends_on: 
    #         - database_ignite
        

volumes:
    pgdata:
        driver: local